AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'add-user

  SAM Template for Online-Order CheckoutService microservice

  '
Globals:
  Function:
    Timeout: 500
    Environment:
      Variables:
        USER_POOL_ID:
          Ref: MyCognitoUserPool
        REGION:
          Ref: AWS::Region
Resources:
  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: sam_api_gateway_cup_auth_cognito_user_pool
      LambdaConfig:
        PreSignUp:
          Fn::GetAtt:
          - PreSignupLambdaFunction
          - Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
      - email
      Schema:
      - AttributeDataType: String
        Name: email
        Required: false
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: sam_api_gateway_cup_auth_cognito_client
      UserPoolId:
        Ref: MyCognitoUserPool
  PreSignupLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: "exports.handler = async (event, context, callback) => {\n  event.response\
        \ = { autoConfirmUser: true }\n  return event\n}\n"
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs12.x
      Timeout: 30
      CodeUri: PreSignupLambdaFunction
  LambdaCognitoUserPoolExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - PreSignupLambdaFunction
        - Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn:
        Fn::Sub: arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${MyCognitoUserPool}
  signupService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://microcredential-serverless-api/3898ac56c74d92f821bcfe5751977274
      FunctionName: OnlineOrderGetCheckout
      Description: 'Online-Order Get Checkout service is to get the checkout details

        '
      Handler: com.cognizant.microcredential.authenticationservice.SignUpServiceApplication::handleRequest
      Runtime: java8
      MemorySize: 512
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'
      Environment:
        Variables:
          ADD_USER_FUNCTION_NAME: OnlineOrderAddUser
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /api/checkout/view/{id}
            Method: get
Outputs:
  CheckoutServiceApi:
    Description: API Gateway endpoint URL for Prod stage OnlineOrder::CheckoutService
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/checkout/view/{id}\n\
        \ https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/checkout/checkout/{id}\n\
        \ https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/checkout/confirm"
  CheckoutServiceGetCheckoutFunction:
    Description: Checkout Service GetCheckout Lambda Functions ARN
    Value:
      Fn::GetAtt:
      - confirmCheckout
      - Arn
  CheckoutServiceUpdateCheckoutFunction:
    Description: Checkout Service Checkout Lambda Functions ARN
    Value:
      Fn::GetAtt:
      - addCheckout
      - Arn
  CheckoutServiceAddCheckoutFunction:
    Description: Checkout Service Confirm Checkout Lambda Functions ARN
    Value:
      Fn::GetAtt:
      - getCheckout
      - Arn
  CheckoutServiceGetCheckoutFunctionIamRole:
    Description: Implicit IAM Role created for Checkout Service Confirm Checkout functions
    Value:
      Fn::GetAtt:
      - confirmCheckoutRole
      - Arn
  CheckoutServiceUpdateCheckoutFunctionIamRole:
    Description: Implicit IAM Role created for Checkout Service Checkout functions
    Value:
      Fn::GetAtt:
      - addCheckoutRole
      - Arn
  CheckoutServiceAddCheckoutFunctionIamRole:
    Description: Implicit IAM Role created for Checkout Service GetCheckout functions
    Value:
      Fn::GetAtt:
      - getCheckoutRole
      - Arn
  CognitoUserPoolId:
    Description: Cognito User Pool Id
    Value:
      Ref: MyCognitoUserPool
  CognitoUserPoolClientId:
    Description: Cognito User Pool Client Id
    Value:
      Ref: CognitoUserPoolClient
