AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  add-user

  Sample SAM Template for add-user

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 500

Resources:
  emailOTPService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: OnlineOrderOTPService
      Handler: com.cognizant.microcredential.emailotpservice.EmailOTPServiceApplication::handleRequest
      Runtime: java8
      MemorySize: 512
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
      Environment:
        Variables:
          MAIL_FROM_ADDRESS: sarath.r93@gmail.com
      Events:
        HelloWorld:
          Type: Api
          Models:
            MailInfo:
              type: object
              required:
                - to
                - message
                - subject
              properties:
                to:
                  type: array
                cc:
                  type: array
                bcc:
                  type: array
                message:
                  type: string
                subject:
                  type: string
          Properties:
            Path: /api/email/otp
            Method: post


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/email/otp"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt emailOTPService.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt emailOTPService.Arn
